"""empty message

Revision ID: 4ee4110a6dbb
Revises: 00ca03cac83d
Create Date: 2020-08-25 14:38:09.902855

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4ee4110a6dbb'
down_revision = '00ca03cac83d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=256), nullable=True))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', mysql.VARCHAR(length=256), nullable=True))
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
