"""empty message

Revision ID: 9faafafd2b00
Revises: 4e73e6b4891a
Create Date: 2020-08-27 14:19:20.137197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9faafafd2b00'
down_revision = '4e73e6b4891a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('collections_ibfk_1', 'collections', type_='foreignkey')
    op.create_foreign_key(None, 'collections', 'posts', ['posts_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'collections', type_='foreignkey')
    op.create_foreign_key('collections_ibfk_1', 'collections', 'users', ['posts_id'], ['id'])
    # ### end Alembic commands ###
